"use client"

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useEffect } from 'react'
import { supabase } from '@/lib/supabase/client'

const DISCLAIMER_TITLE = 'BIR & Tax Responsibility Disclaimer'
const DISCLAIMER_BODY = `I acknowledge and agree that this POS system is provided as a sales, inventory, and reporting tool only.`
const DISCLAIMER_BULLETS = [
  'The POS system is NOT BIR-registered and NOT BIR-certified',
  'Any receipt generated by the system is NOT an official BIR receipt',
  'I am solely responsible for business registration with BIR, issuance of BIR-registered official receipts (OR), and all tax computation, filing, and payment.'
]
const DISCLAIMER_EXTRA = `I agree that the POS provider is not liable for penalties, fines, audit findings, or violations related to my business’ BIR compliance.`
const DISCLAIMER_CONCLUDE = `By proceeding, I confirm I fully understand and accept these terms.`

const STORAGE_FULL_TEXT = `${DISCLAIMER_TITLE}\n\n${DISCLAIMER_BODY}\nI understand that:\n- ${DISCLAIMER_BULLETS.join('\n- ')}\n${DISCLAIMER_EXTRA}\n${DISCLAIMER_CONCLUDE}`

export default function BirAcceptPage() {
  const [checked, setChecked] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [submitted, setSubmitted] = useState(false)
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!checked) return setError('You must accept the disclaimer to proceed')
    setLoading(true)
    setError(null)
    try {
      // include Authorization bearer token when available (auth stored in client session)
      let token: string | null = null
      try {
        const { data: sessionData } = await supabase.auth.getSession()
        token = (sessionData as any)?.session?.access_token ?? null
      } catch (e) {}

      const headers: Record<string, string> = { 'Content-Type': 'application/json' }
      if (token) headers['Authorization'] = `Bearer ${token}`

      const res = await fetch('/api/accept-bir', {
        method: 'POST',
        headers,
        body: JSON.stringify({ disclaimer_version: '2026-01-14-v1', disclaimer_text: STORAGE_FULL_TEXT })
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data?.error || 'Failed to record acceptance')
      setSubmitted(true)
    } catch (err: any) {
      setError(err?.message || String(err))
    } finally {
      setLoading(false)
    }
  }

  // If submission recorded, poll check-bir and redirect when admin approves
  useEffect(() => {
    if (!submitted) return
    let mounted = true
    const interval = setInterval(async () => {
      try {
        const res = await fetch('/api/check-bir')
        if (!res.ok) return
        const j = await res.json()
        if (mounted && j.accepted && j.approved) {
          // approved: send user to dashboard
          window.location.href = '/dashboard'
        }
      } catch (e) {
        // ignore polling errors
      }
    }, 5000)
    return () => { mounted = false; clearInterval(interval) }
  }, [submitted])

  // Check client session to show helpful auth state
  useEffect(() => {
    let mounted = true
    ;(async () => {
      try {
        const { data } = await supabase.auth.getSession()
        const token = (data as any)?.session?.access_token ?? null
        if (!mounted) return
        setIsAuthenticated(!!token)
      } catch (e) {
        if (mounted) setIsAuthenticated(false)
      }
    })()
    return () => { mounted = false }
  }, [])

  return (
    <main className="min-h-screen flex items-center justify-center bg-slate-50 py-12">
      <div className="w-full max-w-3xl px-6">
        <div className="bg-white shadow-xl rounded-2xl overflow-hidden grid grid-cols-1 md:grid-cols-2">
          <div className="p-10 bg-gradient-to-b from-emerald-600 to-emerald-400 text-white">
            <div className="max-w-md">
              <div className="w-14 h-14 rounded-full bg-white/20 mb-6 flex items-center justify-center text-2xl font-bold">B</div>
              <h1 className="text-2xl font-semibold mb-3">{DISCLAIMER_TITLE}</h1>
              <p className="text-sm opacity-90 mb-4">{DISCLAIMER_BODY}</p>

              <div className="text-sm space-y-3">
                <p className="font-medium">I understand that:</p>
                <ul className="list-disc ml-5 space-y-1">
                  {DISCLAIMER_BULLETS.map((b) => (
                    <li key={b} className="leading-snug">{b}</li>
                  ))}
                </ul>

                <p className="mt-3 opacity-90">{DISCLAIMER_EXTRA}</p>
                <p className="mt-3 font-semibold">{DISCLAIMER_CONCLUDE}</p>
              </div>
            </div>
          </div>

          <div className="p-10 flex items-center">
            <div className="w-full">
              <div className="max-w-md mx-auto">
                {!submitted ? (
                  <form onSubmit={handleSubmit} className="space-y-6">
                    <p className="text-sm text-slate-600">To use the POS you must acknowledge the disclaimer below. After you submit, an administrator will review and activate your shop.</p>

                    <label className="flex items-start gap-3 mt-2">
                      <input type="checkbox" className="mt-1 h-4 w-4" checked={checked} onChange={e => setChecked(e.target.checked)} />
                      <div className="text-sm">I have read and agree to the terms above.</div>
                    </label>

                    {error && <div className="text-red-600">{error}</div>}
                    {isAuthenticated === false && (
                      <div className="text-red-600">Not authenticated — <a href="/login" className="text-indigo-600 underline">Sign in</a> to submit acceptance.</div>
                    )}

                    <div className="flex flex-col sm:flex-row items-center sm:items-stretch gap-3">
                      <button type="submit" disabled={!checked || loading || isAuthenticated === false} className="flex-1 inline-flex items-center justify-center px-4 py-3 bg-emerald-600 text-white rounded-md shadow hover:bg-emerald-700 disabled:opacity-60">
                        {loading ? 'Submitting — Await admin approval…' : 'Submit Acceptance — Await Admin Approval'}
                      </button>
                      <a href="/" className="text-sm text-slate-500 self-center">Cancel</a>
                    </div>
                    <div className="pt-2 text-xs text-slate-400">Your acceptance will be reviewed by an administrator before POS activation.</div>
                  </form>
                ) : (
                  <div className="space-y-4 text-center">
                    <h3 className="text-lg font-medium">Submission recorded</h3>
                    <p className="text-sm text-slate-600">Thank you. Your acceptance has been recorded and is awaiting administrative approval. You will be able to use the POS once an admin approves your activation.</p>
                    <div>
                      <a href="/" className="inline-block px-4 py-2 bg-slate-100 rounded-md text-sm">Return home</a>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
